---
title: "CEE218X_A9_StephanieGady"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: fill
editor_options: 
  chunk_output_type: console
---

```{r global, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(leaflet)
library(sf)
library(plotly)
library(shiny)

#pge_data_raw variable is already given, no need to create variable
pge_data_raw <- readRDS("pge_data_raw.rds")

#use libraries and functions that we are already aware of to create bay_zips
bay_zips <- readRDS("bay_zips.rds")

pge_data <-
  pge_data_raw %>% 
  filter(
    CUSTOMERCLASS %in% c(
      "Elec- Commercial",
      "Elec- Residential",
      "Gas- Commercial",
      "Gas- Residential"
    )
  ) %>% 
  group_by(
    MONTH, 
    YEAR, 
    CUSTOMERCLASS
  ) %>% 
  summarize(
    TOTALKBTU = sum(TOTALKBTU, na.rm = T)
  ) %>% 
  mutate(
    DATE = 
      paste(
        YEAR,
        MONTH, 
        "01",
        sep="-"
      ) %>% as.Date()
  )
```

Inputs {.sidebar}
-------------------------------------
```{r}
selectInput(
  inputId = "year", 
  label = "Years:",
  choices = c(2017,2018,2019,2020), 
  selected = 2020
)
selectInput(
  inputId = "class", 
  label = "Customer Class:",
  choices = c("Elec- Commercial", "Elec- Residential", "Gas- Commercial", "Gas- Residential"), 
  selected = "Elec- Commercial"
)
```

Column
-------------------------------------

### Monthly consumption

```{r}
plotlyOutput("plot")
```

```{r, context = "server"}
observeEvent({
  input$year
  input$class
  },{
chart <- pge_data %>% 
  filter(
    CUSTOMERCLASS == input$class,
      YEAR %in% input$year
    ) %>% 
  ggplot(
    aes(
      x = MONTH,
      y = TOTALKBTU/1e9
    )
  ) +
  geom_line(
    aes(
      color = YEAR %>% factor()
    )
  ) +
  scale_x_discrete(
    limits = c(
      "Jan",
      "Feb",
      "Mar",
      "Apr",
      "May",
      "Jun",
      "Jul",
      "Aug",
      "Sep",
      "Oct",
      "Nov",
      "Dec"
    )
  ) +
  labs(
    x = "",
    y = "Total kBTUs (billions)",
    title = paste0(input$class, " Consumption in the Bay Area"),
    color = "Year"
  ) + 
  theme(legend.position = "Bottom")
  output$plot <- renderPlotly({
    chart %>% 
      ggplotly() %>% 
      config(displayModeBar = F)
  })
})
```

Column
-------------------------------------

### ZCTA consumption

```{r}
leafletOutput("map")
```

```{r, context = "server"}
observeEvent(input$year, {
  pge_res_elec <-
    pge_data_raw %>% 
    filter(
      CUSTOMERCLASS == input$class,
      YEAR == input$year
    ) %>% 
    mutate(
      ZIPCODE = ZIPCODE %>% as.character()
    ) %>% 
    group_by(ZIPCODE) %>% 
    summarize(
      TOTALKBTU = sum(TOTALKBTU, na.rm = T)
    ) %>% 
    right_join(
      bay_zips %>% select(GEOID10),
      by = c("ZIPCODE" = "GEOID10")
    ) %>% 
    st_as_sf() %>% 
    st_transform(4326)
  
  res_pal <- colorNumeric(
    palette = "Reds",
    domain = 
      pge_res_elec$TOTALKBTU
  )
  
  output$map <- renderLeaflet({
    leaflet() %>% 
      addProviderTiles(provider = providers$CartoDB.Positron) %>% 
      addPolygons(
        data = pge_res_elec,
        fillColor = ~res_pal(TOTALKBTU),
        color = "white",
        opacity = 0.5,
        fillOpacity = 0.5,
        weight = 1,
        label = ~paste0(
          round(TOTALKBTU), 
          " kBTU total in ",
          ZIPCODE
        ),
        highlightOptions = highlightOptions(
          weight = 2,
          opacity = 1
        )
      ) %>% 
      addLegend(
        data = pge_res_elec,
        pal = res_pal,
        values = ~TOTALKBTU,
        title = paste0("Total Residential<br>Electricity (kBTU), ", input$year)
      )
  })
})
```